version: "3"

# All available services
services:

  postgres:
    container_name: "sql-workshop_postgres"
    restart: "always"
    image: postgres
    env_file: ./work/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./work:/opt/work
    ports:
      - 5432:5432

  metabase:
    container_name: "sql-workshop_metabase"
    restart: "always"
    image: metabase/metabase
    volumes:
      - metabase-data:/metabase.db:cached
    ports:
      - 3000:3000
    depends_on:
      - postgres

  jupyter:
    container_name: "sql-workshop_jupyter"
    env_file: ./work/.env
    build:
      context: ./docker/jupyter
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./work:/opt/work
    ports:
      - "8888:8888"
    depends_on:
      - postgres

volumes:
    postgres-data:
    metabase-data: